import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 9,
    paddingTop: 30,
    paddingBottom: 40,
    paddingHorizontal: 30,
    color: "#111",
  },
  watermarkBanner: {
    backgroundColor: "#c00",
    color: "#fff",
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
    textAlign: "center",
    padding: "6 8",
    marginBottom: 12,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  logo: {
    width: 60,
    height: 60,
    objectFit: "contain",
  },
  issuerBlock: {
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-start",
  },
  issuerName: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
  },
  issuerMeta: {
    fontSize: 8,
    color: "#555",
  },
  invoiceMeta: {
    textAlign: "right",
  },
  invoiceMetaLabel: {
    fontSize: 8,
    color: "#555",
  },
  invoiceMetaValue: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
  },
  section: {
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    backgroundColor: "#f0f0f0",
    padding: "3 6",
    marginBottom: 4,
  },
  receiverGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  receiverField: {
    width: "48%",
  },
  receiverLabel: {
    fontSize: 7,
    color: "#666",
  },
  receiverValue: {
    fontSize: 9,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#e0e0e0",
    padding: "3 4",
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
  },
  tableRow: {
    flexDirection: "row",
    padding: "3 4",
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
  },
  tableRowAlt: {
    flexDirection: "row",
    padding: "3 4",
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
    backgroundColor: "#fafafa",
  },
  colDescription: { flex: 3, fontSize: 8 },
  colQty: { flex: 1, fontSize: 8, textAlign: "right" },
  colPrice: { flex: 1, fontSize: 8, textAlign: "right" },
  colDiscount: { flex: 1, fontSize: 8, textAlign: "right" },
  colTax: { flex: 1, fontSize: 8, textAlign: "right" },
  colTotal: { flex: 1, fontSize: 8, textAlign: "right" },
  taxBreakdown: {
    marginTop: 8,
    alignSelf: "flex-end",
    width: 220,
  },
  totalsBox: {
    marginTop: 4,
    alignSelf: "flex-end",
    width: 220,
    padding: "6 8",
    backgroundColor: "#e8e8e8",
    borderTopWidth: 1,
    borderTopColor: "#999",
  },
  totalsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  totalsLabel: {
    fontSize: 8,
  },
  totalsValue: {
    fontSize: 8,
    textAlign: "right",
  },
  grandTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
    paddingTop: 4,
    borderTopWidth: 0.5,
    borderTopColor: "#999",
  },
  grandTotalLabel: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
  },
  grandTotalValue: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
  },
  fiscalFooter: {
    marginTop: 20,
    paddingTop: 8,
    borderTopWidth: 0.5,
    borderTopColor: "#ccc",
  },
  fiscalFooterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  fiscalFooterLabel: {
    fontSize: 7,
    color: "#666",
    width: 80,
  },
  fiscalFooterValue: {
    fontSize: 7,
    fontFamily: "Courier",
    flex: 1,
  },
  qrPlaceholder: {
    width: 60,
    height: 60,
    borderWidth: 1,
    borderColor: "#999",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  qrPlaceholderText: {
    fontSize: 6,
    color: "#999",
    textAlign: "center",
  },
  watermarkFooter: {
    position: "absolute",
    bottom: 20,
    left: 30,
    right: 30,
    textAlign: "center",
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#c00",
    borderTopWidth: 0.5,
    borderTopColor: "#ccc",
    paddingTop: 4,
  },
});
