import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: "Helvetica", fontSize: 10 },
  title: { fontSize: 18, fontWeight: "bold", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#666", marginBottom: 16 },
  filtersSection: { marginBottom: 12 },
  filtersTitle: { fontSize: 9, fontWeight: "bold", marginBottom: 4, color: "#444" },
  filterChips: { flexDirection: "row", flexWrap: "wrap", gap: 4 },
  chip: { backgroundColor: "#e8f4fd", borderRadius: 3, paddingHorizontal: 6, paddingVertical: 2, fontSize: 8 },
  table: { marginTop: 8 },
  tableHeader: { flexDirection: "row", backgroundColor: "#1565C0", color: "white", paddingVertical: 5, paddingHorizontal: 4 },
  tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#ccc", paddingVertical: 4, paddingHorizontal: 4 },
  tableRowEven: { backgroundColor: "#f9f9f9" },
  colDate: { width: "12%", fontSize: 8 },
  colRecibo: { width: "12%", fontSize: 8 },
  colTicket: { width: "12%", fontSize: 8 },
  colCliente: { width: "15%", fontSize: 8 },
  colCobrador: { width: "15%", fontSize: 8 },
  colMetodo: { width: "10%", fontSize: 8 },
  colMonto: { width: "12%", fontSize: 8, textAlign: "right" },
  colEstado: { width: "12%", fontSize: 8 },
  totalsSection: { marginTop: 16, borderTopWidth: 1, borderTopColor: "#333", paddingTop: 8 },
  totalsTitle: { fontSize: 11, fontWeight: "bold", marginBottom: 6 },
  totalsRow: { flexDirection: "row", marginBottom: 3 },
  totalsLabel: { width: 160, fontSize: 9, color: "#555" },
  totalsValue: { fontSize: 9, fontWeight: "bold" },
  footer: { position: "absolute", bottom: 20, left: 30, right: 30, fontSize: 8, color: "#888", textAlign: "center" },
  emptyMsg: { marginTop: 40, textAlign: "center", color: "#888", fontSize: 12 },
  headerCol: { color: "white", fontWeight: "bold", fontSize: 8 },
});
